# Generated by Django 4.2.3 on 2026-03-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="billed_at",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="invoice",
        ),
        migrations.AddField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("FINISHED", "Finished"),
                    ("CANCELED", "Canceled"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
