# Generated by Django 4.2.3 on 2026-05-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="meeting_requested_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
