# Generated by Django 4.2.3 on 2026-05-29 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("company_website", models.URLField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=120)),
                ("team_size", models.CharField(blank=True, max_length=80)),
                ("applicant_name", models.CharField(max_length=255)),
                ("applicant_email", models.EmailField(max_length=254)),
                ("applicant_phone", models.CharField(blank=True, max_length=32)),
                ("applicant_title", models.CharField(blank=True, max_length=120)),
                ("use_case", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                        ],
                        default="SUBMITTED",
                        max_length=16,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
