# Generated by Django 4.2.3 on 2026-03-05 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_must_change_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyaccount",
            name="company_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
