# Generated by Django 4.2.3 on 2026-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_companyaccount_company_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_profile",
            field=models.BooleanField(default=False),
        ),
    ]
